### ISSUE TITLE
Can you update to latest version?

### ISSUE THREAD

**Issue by CormacZ** [ChristopherHaws/mc-xaero-map-spigot#5]

**Comment by ChristopherHaws** [comment]
Hey there! I am planning on updating all my mods and plugins this weekend hopefully. Stay tuned! :)

**Comment by CormacZ** [comment]
😀Thanks

**Comment by sehmee** [comment]
Do we still need this mod? I read that adding the spigot version to the server does some things too. "This mod is mostly client-sided. Installing it on the server side is optional for some additional features like world identification." - [here](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)

**Comment by ChristopherHaws** [comment]
I have not had a chance to update the mod yet. It is still needed if you are running a spigot based server behind a proxy. This mod mimics the server side functionality of Xaeros (which you can only run using Fabric) which sends a packet to the client every time they join or switch servers or dimensions so that the user always has the correct map loaded.

I will take a look sometime this week to see what broke in the latest version. Probably something simple since this mod is only around 50 lines of code.

**Comment by sehmee** [comment]
> I have not had a chance to update the mod yet. It is still needed if you are running a spigot based server behind a proxy. This mod mimics the server side functionality of Xaeros (which you can only run using Fabric) which sends a packet to the client every time they join or switch servers or dimensions so that the user always has the correct map loaded.
> 
> 
> 
> I will take a look sometime this week to see what broke in the latest version. Probably something simple since this mod is only around 50 lines of code.

My Spigot server is not behind a proxy. Using the mod for Fabric and is on the server too. It does work and we can see all players on the map. What is the benefit of using your mod in my case?

**Comment by davepgreene** [comment]
> I will take a look sometime this week to see what broke in the latest version. Probably something simple since this mod is only around 50 lines of code.

Of your code, nothing! I rebuilt this to support Spigot API v1.20 and everything worked just fine. However, the `kr.entree.spigradle` gradle plugin has a fun little yaml-related edge case where the class that writes out the `plugin.yml` doesn't quote things that look like numbers. 

Consequently, updating `spigotApiVersion` in `gradle.properties` results in the spigradle tasks writing out a `plugin.yml` file containing `api-version: 1.20`, Paper/Spigot reading the `api-version` property as a double and, when `toString()` is called on it, outputting `1.2` which causes it to throw `org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.2`. 

See https://www.spigotmc.org/threads/tutor-solving-unsupported-api-version-1-2-error-in-1-20-plugins.607378/ for more details.

This patch fixes it until the spigradle plugin addresses https://github.com/spigradle/spigradle/issues/88.
```diff
diff --git a/build.gradle b/build.gradle
index ed6b3ec..791a6a0 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,5 +1,5 @@
 plugins {
-    id 'kr.entree.spigradle' version '2.4.2'
+    id 'kr.entree.spigradle' version '2.4.3'
     id 'com.github.johnrengelman.shadow' version '7.1.2'
     id 'java'
 }
@@ -37,6 +37,15 @@ spigot {
     }
 }
 
+// Override the task configuration in spigradle that generates plugin.yml to make
+// sure that we are properly quoting numbers when we write the file so that 1.20
+// isn't inferred as a number and truncated to 1.2.
+tasks.generateSpigotDescription.configure {
+    it.yamlOptions = [
+            "ALWAYS_QUOTE_NUMBERS_AS_STRINGS": true,
+    ] as Map
+}
+
 shadowJar {
     //archiveClassifier.set("")
     relocate 'org.bstats', 'dev.chaws.xaero.map.spigot'
diff --git a/gradle.properties b/gradle.properties
index 6e1a67d..9e91fe0 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -2,6 +2,6 @@ group = dev.chaws
 packageName = xaero-map-spigot
 pluginName = xaero-map-spigot
 authors = Chaws
-mcVersion = 1.19.2
-spigotApiVersion = 1.19
+mcVersion = 1.20
+spigotApiVersion = 1.20
 version = 1.0.0
```

I'm not sure if there's any other work that might have to be done to maintain support with older versions but I'm running this on my home servers and everything is working perfectly.

**Comment by ChristopherHaws** [comment]
@davepgreene Great to hear. I will try to apply the patch this weekend and get it uploaded! Sorry for the delay, I have been super busy and just got back from a vacation. :)

**Comment by CormacZ** [comment]
Yay

**Comment by samuelh2005** [comment]
The existing version of this plugin looks like it works fine in 1.20.1 (nearly latest),

So far this plugin seems like an easier to use version of https://modrinth.com/plugin/worldnamepacket. Thank you!

**Comment by ChristopherHaws** [comment]
Closing the issue as there have been no breaking changes so this plugin should continue to work as expected in newer versions.
